[package]
name = "elements"
version = "0.10.0"
authors = ["Andrew Poelstra <apoelstra@blockstream.com>"]
description = "Library with support for de/serialization, parsing and executing on data structures and network messages related to Elements"
license = "CC0-1.0"
homepage = "https://github.com/ElementsProject/rust-elements/"
repository = "https://github.com/ElementsProject/rust-elements/"
documentation = "https://docs.rs/elements/"

[features]
"serde-feature" = [
    "bitcoin/use-serde",
    "serde"
]
"fuzztarget" = []

[dependencies]
bitcoin = { git = "git://github.com/stevenroose/rust-bitcoin", branch = "devel" }

[dependencies.serde]
version = "1.0"
optional = true

[dev-dependencies]
rand = "0.6.5"
serde_json = "1"
